spring.application.name=frotaFront
server.port=8081

# ATUALIZA O HTML AO SALVAR
# Faz o Thymeleaf ler os arquivos HTML direto da pasta de c\u00f3digo-fonte
spring.thymeleaf.prefix=file:src/main/resources/templates/
# Desativa o cache de templates
spring.thymeleaf.cache=false
